package com.russellworld.russellboard.utilits

const val SIGN_UP_STATE = 0
const val SIGN_IN_STATE = 1
const val SIGN_IN_REQUEST_CODE = 135

const val ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_IN_USE"
const val ERROR_INVALID_EMAIL = "ERROR_EMAIL_ALREADY_IN_USE"
const val ERROR_WRONG_PASSWORD = "ERROR_EMAIL_ALREADY_IN_USE"
const val ERROR_ERROR_WEAK_PASSWORD = "ERROR_EMAIL_ALREADY_IN_USE"
const val ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"